version: '3.8'

networks:
  traefik-network:
    name: "traefik-network"
    external: true

services:
  server:
    image: nicolargo/glances:4.3.2-full
    command: glances -w
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: "host"
    environment:
      - TZ=Europe/Zagreb  # Adjust to your timezone
    networks:
      - traefik-network
